### ISSUE TITLE
mqtt credentials

### ISSUE THREAD

**Issue by arturol76** [ManCaveMade/ESP-DSC-MQTT#1]
Hi,
in case the mqtt server requires usr/psw (like in my case), the following must be added during initialization:

mqttClient.setCredentials(MQTT_USER, MQTT_PASS);

...otherwise the client won't connect.

**Comment by uberflyx** [comment]
Hi, yes good point! I will add that in - I recently restricted my MQTT server to auth only and it stopped working. I didn't think about it much yet but this will solve my problem. Thanks for the heads up.
